#include <algorithm>
#include <iomanip>
#include <iostream>
#include <string>
#include <vector>
#include <numeric>

using std::cin;
using std::copy;
using std::cout;
using std::endl;
using std::left;
using std::right;
using std::setprecision;
using std::setw;
using std::string;
using std::swap;
using std::vector;
using std::sort;
using std::accumulate;
